# 四則演算

In [4]:
# 変数定義
x = 1

# かけ算はアスタリスク
y = 100 * x
print(y) # 100

# 元の値に 2 を足す
y += 2 # y = y + 2
print(y)

# 元の値から引く
y -= 22
print(y) # 80

# 元の値にかける
y *= 3
print(y) # 240

# 元の値を割る
y /= 10
print(y) # 24.0 実数になる

# 元の値のあまりを取る
y %= 5
print(y) # 4.0

100
102
80
240
24.0
4.0


# Numpy

In [ ]:
import numpy as np

# 円周率
print(np.pi)
# 文字列にする
print(str(np.pi))

# フォーマット文字列
print('{:10.4f}'.format(np.pi))
print('{:10.8f}'.format(np.pi))

## 多項式

In [29]:
import numpy as np

# 
p1 = np.poly1d([1, 2, 3])
p2 = np.poly1d([2, 3, 4, 5, 6])
p3 = np.poly1d([0, 1], True)
print('配列の 0 番目が最高階の係数')
print(p1)
print('第 2 引数を True にすると指定配列を根とする多項式になる')
print(p3)

print('多項式の係数の配列')
print(p1.c)
print('多項式の k 番目の係数')
print(p1[1])

print('多項式の次数')
print(p1.order)

print('多項式の評価')
print(np.polyval(p1, 5))
print(p1(5))

print('多項式の和')
print(np.polyadd(p1, p2))

print('多項式の差: 第1引数 - 第2引数')
print(np.polysub(p1, p2))

print('多項式の積')
print(np.polymul(p1, p2))
print('普通の積記号でも大丈夫：他も同じ')
print(p1 * p2)

print('多項式のべき')
print(p1 ** 2)

q = np.polydiv(p2, p1)
print('多項式の割り算')
print(q)
print('多項式の商')
print(q[0])
print('多項式の割り算：あまり')
print(q[1])

print('多項式の導多項式')
for i in range(0, 6):
    print('第 {} 導関数'.format(i))
    print(np.polyder(p2, m = i))

print('多項式の積分')
print(np.polyint(p1))

print('多項式の根')
print(np.sort(np.roots(p2)))
print(np.sort((p2.r)))

配列の 0 番目が最高階の係数
   2
1 x + 2 x + 3
第 2 引数を True にすると指定配列を根とする多項式になる
   2
1 x - 1 x
多項式の係数の配列
[1 2 3]
多項式の k 番目の係数
2
多項式の次数
2
多項式の評価
38
38
多項式の和
   4     3     2
2 x + 3 x + 5 x + 7 x + 9
多項式の差: 第1引数 - 第2引数
    4     3     2
-2 x - 3 x - 3 x - 3 x - 3
多項式の積
   6     5      4      3      2
2 x + 7 x + 16 x + 22 x + 28 x + 27 x + 18
普通の積記号でも大丈夫：他も同じ
   6     5      4      3      2
2 x + 7 x + 16 x + 22 x + 28 x + 27 x + 18
多項式のべき
   4     3      2
1 x + 4 x + 10 x + 12 x + 9
多項式の割り算
(poly1d([ 2., -1.,  0.]), poly1d([ 8.,  6.]))
多項式の商
   2
2 x - 1 x
多項式の割り算：あまり
 
8 x + 6
多項式の導多項式
第 0 導関数
   4     3     2
2 x + 3 x + 4 x + 5 x + 6
第 1 導関数
   3     2
8 x + 9 x + 8 x + 5
第 2 導関数
    2
24 x + 18 x + 8
第 3 導関数
 
48 x + 18
第 4 導関数
 
48
第 5 導関数
 
0
多項式の積分
        3     2
0.3333 x + 1 x + 3 x
多項式の根
[-1.08691531-0.76526803j -1.08691531+0.76526803j  0.33691531-1.25867457j
  0.33691531+1.25867457j]
[-1.08691531-0.76526803j -1.08691531+0.76526803j  0.33691531-1.25867457j
  0.33691531+1.25867457j]


## 配列
配列のすべての要素に対して同じ処理ができることがある。
高速な上に凄まじく便利なので使い慣れる一択しかない。

In [9]:
a = np.array([1.7, 233.3234235, 21, 234.23421, 2.621321])
# 配列の全ての数に対して切り捨て、切り上げ、四捨五入
print(np.trunc(a))
print(np.ceil(a))
print(np.around(a))

3.141592653589793
3.141592653589793
    3.1416
3.14159265
[   1.  233.   21.  234.    2.]
[   2.  234.   21.  235.    3.]
[   2.  233.   21.  234.    3.]


### 関数

In [21]:
import numpy as np
from scipy.special import factorial

print('階乗')
args = np.arange(10)
print(np.math.factorial(6))
print('scipy.special の factorial は引数に配列を当てられる: numpy だと駄目らしい')
print(factorial(args))

print('指数')
# np.power(x1, x2)
# x1 は底、x2 は指数：両方とも配列を入れられる
# いろいろなサンプルは順次追記
exponents = np.arange(0, 10, 0.1)
powers = np.power(np.e, exponents)
print(powers)


print('対数')
# 自然対数、常用対数、2 進対数の関数がある
args = np.arange(0.1, 10, 0.1)
print(np.log(np.e))
print(np.log10(10))
print(np.log2(2))
print('log も配列を食わせて配列を返せる')
print(np.log(args))
print(np.log10(args))
print(np.log2(args))

print('''sin, cos, tan, arcsin, arccos, arctan などもある！''')

階乗
720
scipy.special の factorial は引数に配列を当てられる: numpy だと駄目らしい
[  1.00000000e+00   1.00000000e+00   2.00000000e+00   6.00000000e+00
   2.40000000e+01   1.20000000e+02   7.20000000e+02   5.04000000e+03
   4.03200000e+04   3.62880000e+05]
指数
[  1.00000000e+00   1.10517092e+00   1.22140276e+00   1.34985881e+00
   1.49182470e+00   1.64872127e+00   1.82211880e+00   2.01375271e+00
   2.22554093e+00   2.45960311e+00   2.71828183e+00   3.00416602e+00
   3.32011692e+00   3.66929667e+00   4.05519997e+00   4.48168907e+00
   4.95303242e+00   5.47394739e+00   6.04964746e+00   6.68589444e+00
   7.38905610e+00   8.16616991e+00   9.02501350e+00   9.97418245e+00
   1.10231764e+01   1.21824940e+01   1.34637380e+01   1.48797317e+01
   1.64446468e+01   1.81741454e+01   2.00855369e+01   2.21979513e+01
   2.45325302e+01   2.71126389e+01   2.99641000e+01   3.31154520e+01
   3.65982344e+01   4.04473044e+01   4.47011845e+01   4.94024491e+01
   5.45981500e+01   6.03402876e+01   6.66863310e+01   7.36997937e+01
   

### 度数とラジアンの変換

In [6]:
# arange で一気に配列を作る
degrees = np.arange(0, 181, 0.1)

print('degrees の表示')
print(degrees)

print('度数をラジアンに変換')
radians = np.deg2rad(degrees)
print(radians)

print('ラジアンを度数に変換')
print(np.rad2deg(radians))

degrees の表示
[  0.00000000e+00   1.00000000e-01   2.00000000e-01 ...,   1.80700000e+02
   1.80800000e+02   1.80900000e+02]
度数をラジアンに変換
[  0.00000000e+00   1.74532925e-03   3.49065850e-03 ...,   3.15380996e+00
   3.15555529e+00   3.15730062e+00]
ラジアンを度数に変換
[  0.00000000e+00   1.00000000e-01   2.00000000e-01 ...,   1.80700000e+02
   1.80800000e+02   1.80900000e+02]
