# この notebook を読み進める前に
TeX 出力のためには次のコードを読み込ませること。

In [2]:
from sympy import *
from IPython.display import display
init_printing()

# Numpy

In [4]:
import numpy as np

# 円周率
display(np.pi)
# 文字列にする
display(str(np.pi))

'3.141592653589793'

### フォーマット文字列

In [5]:
display('{:10.4f}'.format(np.pi))
display('{:10.8f}'.format(np.pi))

'    3.1416'

'3.14159265'

## 多項式

In [7]:
import numpy as np

p1 = np.poly1d([1, 2, 3])
p2 = np.poly1d([2, 3, 4, 5, 6])
p3 = np.poly1d([0, 1], True)

### 配列の 0 番目が最高階の係数

In [7]:
display(p1)

poly1d([1, 2, 3])

第 2 引数を True にすると指定配列を根とする多項式になる

In [8]:
display(p3)

poly1d([ 1., -1.,  0.])

多項式の係数の配列

In [9]:
display(p1.c)

array([1, 2, 3])

多項式の $k$ 番目の係数

In [11]:
display(p1[1])

2

多項式の次数

In [13]:
display(p1.order)

多項式の評価

In [14]:
display(np.polyval(p1, 5))
display(p1(5))

38

38

多項式の和

In [15]:
display(np.polyadd(p1, p2))

poly1d([2, 3, 5, 7, 9])

多項式の差: 第1引数 - 第2引数

In [17]:
display(np.polysub(p1, p2))

poly1d([-2, -3, -3, -3, -3])

多項式の積

In [19]:
display(np.polymul(p1, p2))

poly1d([ 2,  7, 16, 22, 28, 27, 18])

普通の積記号でも大丈夫：他も同じ

In [21]:
display(p1 * p2)

poly1d([ 2,  7, 16, 22, 28, 27, 18])

多項式のべき

In [22]:
display(p1 ** 2)

poly1d([ 1,  4, 10, 12,  9])

多項式の割り算

In [24]:
q = np.polydiv(p2, p1)
display(q)

(poly1d([ 2., -1.,  0.]), poly1d([ 8.,  6.]))

多項式の商

In [25]:
display(q[0])

poly1d([ 2., -1.,  0.])

多項式の割り算：あまり

In [26]:
display(q[1])

poly1d([ 8.,  6.])

In [8]:
display('多項式の導多項式')
for i in range(0, 6):
    display('第 {} 導関数'.format(i))
    display(np.polyder(p2, m = i))

'多項式の導多項式'

'第 0 導関数'

poly1d([2, 3, 4, 5, 6])

'第 1 導関数'

poly1d([8, 9, 8, 5])

'第 2 導関数'

poly1d([24, 18,  8])

'第 3 導関数'

poly1d([48, 18])

'第 4 導関数'

poly1d([48])

'第 5 導関数'

poly1d([ 0.])

多項式の積分

In [27]:
display(np.polyint(p1))

poly1d([ 0.33333333,  1.        ,  3.        ,  0.        ])

多項式の根

In [28]:
display(np.sort(np.roots(p2)))
display(np.sort((p2.r)))

array([-1.08691531-0.76526803j, -1.08691531+0.76526803j,
        0.33691531-1.25867457j,  0.33691531+1.25867457j])

array([-1.08691531-0.76526803j, -1.08691531+0.76526803j,
        0.33691531-1.25867457j,  0.33691531+1.25867457j])

## 配列
配列のすべての要素に対して同じ処理ができることがある。
高速な上に凄まじく便利なので使い慣れる一択しかない。

In [29]:
a = np.array([1.7, 233.3234235, 21, 234.23421, 2.621321])
# 配列の全ての数に対して切り捨て、切り上げ、四捨五入
display(np.trunc(a))

array([   1.,  233.,   21.,  234.,    2.])

In [30]:
display(np.ceil(a))

array([   2.,  234.,   21.,  235.,    3.])

In [31]:
display(np.around(a))

array([   2.,  233.,   21.,  234.,    3.])

### 関数

In [33]:
import numpy as np
from scipy.special import factorial

### 階乗

In [34]:
args = np.arange(10)
display(np.math.factorial(6))

scipy.special の factorial は引数に配列を当てられる: numpy だと駄目らしい

In [35]:
display(factorial(args))

array([  1.00000000e+00,   1.00000000e+00,   2.00000000e+00,
         6.00000000e+00,   2.40000000e+01,   1.20000000e+02,
         7.20000000e+02,   5.04000000e+03,   4.03200000e+04,
         3.62880000e+05])

指数

In [36]:
# np.power(x1, x2)
# x1 は底、x2 は指数：両方とも配列を入れられる
# いろいろなサンプルは順次追記
exponents = np.arange(0, 10, 0.1)
powers = np.power(np.e, exponents)
display(powers)

array([  1.00000000e+00,   1.10517092e+00,   1.22140276e+00,
         1.34985881e+00,   1.49182470e+00,   1.64872127e+00,
         1.82211880e+00,   2.01375271e+00,   2.22554093e+00,
         2.45960311e+00,   2.71828183e+00,   3.00416602e+00,
         3.32011692e+00,   3.66929667e+00,   4.05519997e+00,
         4.48168907e+00,   4.95303242e+00,   5.47394739e+00,
         6.04964746e+00,   6.68589444e+00,   7.38905610e+00,
         8.16616991e+00,   9.02501350e+00,   9.97418245e+00,
         1.10231764e+01,   1.21824940e+01,   1.34637380e+01,
         1.48797317e+01,   1.64446468e+01,   1.81741454e+01,
         2.00855369e+01,   2.21979513e+01,   2.45325302e+01,
         2.71126389e+01,   2.99641000e+01,   3.31154520e+01,
         3.65982344e+01,   4.04473044e+01,   4.47011845e+01,
         4.94024491e+01,   5.45981500e+01,   6.03402876e+01,
         6.66863310e+01,   7.36997937e+01,   8.14508687e+01,
         9.00171313e+01,   9.94843156e+01,   1.09947172e+02,
         1.21510418e+02,

### 対数

自然対数、常用対数、2 進対数の関数がある.

In [37]:
args = np.arange(0.1, 10, 0.1)
display(np.log(np.e))
display(np.log10(10))
display(np.log2(2))

log も配列を食わせて配列を返せる

In [38]:
print(np.log(args))
print(np.log10(args))
print(np.log2(args))

[-2.30258509 -1.60943791 -1.2039728  -0.91629073 -0.69314718 -0.51082562
 -0.35667494 -0.22314355 -0.10536052  0.          0.09531018  0.18232156
  0.26236426  0.33647224  0.40546511  0.47000363  0.53062825  0.58778666
  0.64185389  0.69314718  0.74193734  0.78845736  0.83290912  0.87546874
  0.91629073  0.95551145  0.99325177  1.02961942  1.06471074  1.09861229
  1.13140211  1.16315081  1.19392247  1.22377543  1.25276297  1.28093385
  1.30833282  1.33500107  1.36097655  1.38629436  1.41098697  1.43508453
  1.45861502  1.48160454  1.5040774   1.5260563   1.54756251  1.56861592
  1.58923521  1.60943791  1.62924054  1.64865863  1.66770682  1.68639895
  1.70474809  1.7227666   1.74046617  1.75785792  1.77495235  1.79175947
  1.80828877  1.82454929  1.84054963  1.85629799  1.87180218  1.88706965
  1.90210753  1.91692261  1.93152141  1.94591015  1.96009478  1.97408103
  1.98787435  2.00148     2.01490302  2.02814825  2.04122033  2.05412373
  2.06686276  2.07944154  2.09186406  2.10413415  2

### sin, cos, tan, arcsin, arccos, arctan などもある！

### 度数とラジアンの変換

In [39]:
# arange で一気に配列を作る
degrees = np.arange(0, 181, 0.1)

degrees の表示

In [40]:
display(degrees)

array([  0.00000000e+00,   1.00000000e-01,   2.00000000e-01, ...,
         1.80700000e+02,   1.80800000e+02,   1.80900000e+02])

度数をラジアンに変換

In [41]:
radians = np.deg2rad(degrees)
display(radians)

array([  0.00000000e+00,   1.74532925e-03,   3.49065850e-03, ...,
         3.15380996e+00,   3.15555529e+00,   3.15730062e+00])

ラジアンを度数に変換

In [42]:
display(np.rad2deg(radians))

array([  0.00000000e+00,   1.00000000e-01,   2.00000000e-01, ...,
         1.80700000e+02,   1.80800000e+02,   1.80900000e+02])