### 2.1　足し算・引き算

In [1]:
import numpy as np
A = np.matrix([[50, 40],[10, 10]])      # 行列A（朝）
B = np. matrix([[30, 100], [20, 15]])   # 行列B（夜）
A+B

matrix([[ 80, 140],
        [ 30,  25]])

### 2.2　行列の実数倍

In [2]:
A = np.matrix([[80, 140], [30, 25]])  # 行列A
0.8 * A   # 0.8×A

matrix([[ 64., 112.],
        [ 24.,  20.]])

### 2.3　掛け算

In [3]:
A = np.matrix([[1, 3], [2, 1]])          # 行列A（掛けられる側）
B = np.matrix([[150, 250], [130, 230]])  # 行列B（掛ける側）
A * B

matrix([[540, 940],
        [430, 730]])

### 2.4　掛け算のルール

In [4]:
A = np.matrix([[1, 3], [2, 1]])  # 行列A（2×2行列）
B = np.matrix([[145], [72]])     # 行列B（2×1行列）
A * B

matrix([[361],
        [362]])

### 2.5　単位行列

In [5]:
A = np.matrix([[1, 3], [2, 1]])  # 行列A
E = np.matrix([[1, 0], [0, 1]])  # 単位行列E
A * E

matrix([[1, 3],
        [2, 1]])

In [6]:
E * A

matrix([[1, 3],
        [2, 1]])

### 2.6　逆行列

In [7]:
A = np.matrix([[5, 3], [2, 1]])  # 行列A
B = np.linalg.inv(A)             # 逆行列（B）を求める
B

matrix([[-1.,  3.],
        [ 2., -5.]])

In [8]:
(A * B).astype(np.int64)

matrix([[1, 0],
        [0, 1]], dtype=int64)

### 2.7　逆行列と連立方程式

In [9]:
A = np.matrix([[5, 3], [2, 1]])  # 行列A（未知数の係数で作った行列）
inv_A = np.linalg.inv(A)   # 行列Aの逆行列
B = np.matrix([[9], [4]])  # 行列B（連立方程式の右辺）
inv_A * B  # 逆行列×行列B

matrix([[ 3.],
        [-2.]])

In [10]:
a = 5  # 行列A（未知数の係数）
b = 3
c = 2
d = 1
s = 9  # 行列B（連立方程式の右辺）
t = 4
k = a*d - b*c  # 逆行列の各要素の分母
x = ((d/k)*s) + ((-b/k)*t)  # 逆行列×行列B
y = ((-c/k)*s) + ((a/k*t))
x, y

(3.0, -2.0)