### 1.3　ベクトルの方向

In [1]:
import math
rad = math.atan2(3, 2)  # 角度を求める（ラジアン）
th = math.degrees(rad)  # 度数法に変換
th

56.309932474020215

### 1.5　ベクトルの演算

In [2]:
import numpy as np
a = np.array([2, 2])  # ベクトルaの成分
b = np.array([2, -1]) # ベクトルbの成分

# 足し算
a + b

array([4, 1])

In [3]:
# 引き算
a - b

array([0, 3])

In [4]:
# 実数倍
>>> 2 * a

array([4, 4])