▲リスト4.1：スカラーの例

In [1]:
a = 1
b = 1.2
c = -0.25
d = 1.2e5  # 1.2x10の5乗 120000

▲リスト4.2：ベクトルをNumPyの一次元配列で表す

In [2]:
import numpy as np

a = np.array([1, 2, 3])  # 1次元配列でベクトルを表す
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


▲リスト4.3：行列をNumPyの2次元配列で表す

In [6]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2×3の行列
print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])  # 3×2の行列
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


▲リスト4.4：3階のテンソルをNumPyの配列で表す

In [4]:
import numpy as np

a = np.array([[[0, 1, 2, 3],
                      [2, 3, 4, 5],
                      [4, 5, 6, 7]],
              
                     [[1, 2, 3, 4],
                      [3, 4, 5, 6],
                      [5, 6, 7, 8]]])  # (2, 3, 4)の3階のテンソル
print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


#### □問題
　Jupyter Notebookのセルに、NumPyでスカラー、ベクトル、行列、3階のテンソルを表す配列をを1つずつ記述し表示してみましょう。

#### □解答例

▲リスト4.5：解答例

In [7]:
import numpy as np

# スカラー
a = 1.5
print(a)

print()

# ベクトル
b = np.array([1, 2, 3, 4, 5])
print(b)

print()

# 行列
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)

print()

# 3階のテンソル
d = np.array([[[0, 1, 2],
               [3, 4, 5],
               [6, 7, 8]],
              
              [[8, 7, 6],
               [5, 4, 3],
               [2, 1, 0]]])
print(d)

1.5

[1 2 3 4 5]

[[1 2 3]
 [4 5 6]]

[[[0 1 2]
  [3 4 5]
  [6 7 8]]

 [[8 7 6]
  [5 4 3]
  [2 1 0]]]
