▲リスト4.10：NumPyを使って行列積を計算する

In [2]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[2, 1],
              [2, 1],
              [2, 1]]) 

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


▲リスト4.11：NumPyを使って要素ごとの積を計算する

In [3]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]]) 

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


#### □問題
　リスト4.12 で、行列aと行列bの行列積、および行列cと行列dの要素ごとの積
を求めましょう。

▲リスト4.12：問題

In [ ]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 行列積



c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 要素ごとの積


#### □解答例

▲リスト4.13：解答例

In [4]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 

b = np.array([[0, 1],
              [1, 2],
              [2, 3]]) 

# 行列積
print(np.dot(a, b))
      
print()

c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]]) 

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]]) 

# 要素ごとの積
print(c*d)

[[ 5  8]
 [ 8 14]]

[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
