▲リスト4.14：行列を転置する

In [1]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6]])  # 行列

print(a.T)  # 転置

[[1 4]
 [2 5]
 [3 6]]


▲リスト4.15：転置した上で、行列積を行う

In [2]:
import numpy as np

a = np.array([[0, 1, 2],
             [1, 2, 3]])  # 2×3の行列
b = np.array([[0, 1, 2],
             [1, 2, 3]])  # 2×3の行列 このままでは行列積ができない

# print(np.dot(a, b))  # 転置しないで行列積をとるとエラー
print(np.dot(a, b.T))  # 転置により行列積が可能に

[[ 5  8]
 [ 8 14]]


#### □問題
　リスト4.16で行列aもしくは行列bを転置し、行列aと行列bの行列積を計算しましょう。

▲リスト4.16：問題

In [3]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 行列積



#### □解答例

▲リスト4.17：解答例

In [5]:
import numpy as np

a = np.array([[0, 1, 2],
              [1, 2, 3]]) 
b = np.array([[0, 1, 2],
              [2, 3, 4]]) 

# 行列積
print(np.dot(a, b.T))

[[ 5 11]
 [ 8 20]]
