▲リスト4.18：`eye()`関数を使って単位行列を作る

In [6]:
import numpy as np

print(np.eye(2))  # 2×2の単位行列
print()
print(np.eye(3))  # 3×3の単位行列
print()
print(np.eye(4))  # 4×4の単位行列

[[1. 0.]
 [0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


▲リスト4.19：`linalg.det()`関数を使って行列式を求める

In [7]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.det(a))  # 行列式が0にならない場合

b = np.array([[1, 2],
              [0, 0]])
print(np.linalg.det(b))  # 行列式が0になる場合

-2.0000000000000004
0.0


▲リスト4.20
：`linalg.inv()`関数を使って逆行列を求める

In [8]:
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
print(np.linalg.inv(a))  # 逆行列

b = np.array([[1, 2],
              [0, 0]])
# print(np.linalg.inv(b))  # 逆行列が存在しないのでエラーが起きる

[[-2.   1. ]
 [ 1.5 -0.5]]


#### □問題
　リスト4.23で行列`a`の行列式を求め、逆行列が存在する場合は逆行列を求めましょう。

▲リスト4.21：問題

In [9]:
import numpy as np

a = np.array([[1, 1],
              [1, 2]]) 

# 行列式


# 逆行列



#### □解答例

▲リスト4.22：解答例

In [10]:
import numpy as np

a = np.array([[1, 1],
              [1, 2]]) 

# 行列式
print(np.linalg.det(a))

print()

# 逆行列
print(np.linalg.inv(a))

1.0

[[ 2. -1.]
 [-1.  1.]]
