▲リスト2.31：NumPyのインポート

In [1]:
import numpy

▲リスト2.32：モジュールに別の名前をつける

In [2]:
import numpy as np

▲リスト2.33：PythonのリストからNumPyの配列を作る

In [3]:
import numpy as np

a = np.array([0, 1, 2, 3, 4, 5])  # PythonのリストからNumPyの配列を作る
print(a) 

[0 1 2 3 4 5]


▲リスト2.34：2重のリストからNumPyの2次元配列を作る

In [4]:
import numpy as np

b = np.array([[0, 1, 2], [3, 4, 5]])  # 2重のリストからNumPyの2次元配列を作る
print(b)

[[0 1 2]
 [3 4 5]]


▲リスト2.35：3重のリストからNumPyの3次元配列を作る

In [11]:
import numpy as np

c = np.array([[[0, 1, 2], [3, 4, 5]], [[5, 4, 3], [2, 1, 0]]])  # 3重のリストからNumPyの3次元配列を作る
print(c)

[[[0 1 2]
  [3 4 5]]

 [[5 4 3]
  [2 1 0]]]


▲リスト2.36：配列を生成する様々な関数

In [12]:
import numpy as np

d = np.zeros(8)  # 0が8個格納された配列
print(d)

e = np.ones(8) # 1が8個格納された配列
print(e)

f = np.arange(8) # 0から7までが格納された配列
print(f)

[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7]


▲リスト2.37：`shape( )`関数により配列の形状を得る

In [13]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2x3の2次元配列
print(np.shape(a))  # aの形状を表示

(2, 3)


▲リスト2.38：`len( )`により一番外側の要素数を得る

In [14]:
print(len(a))  # aの行数を得る

2


▲リスト2.39：配列と数値の演算

In [15]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2次元配列

print(a) 
print()
print(a + 3)  # 各要素に3を足す
print()
print(a * 3)  # 各要素に3を掛ける

[[0 1 2]
 [3 4 5]]

[[3 4 5]
 [6 7 8]]

[[ 0  3  6]
 [ 9 12 15]]


▲リスト2.40：配列同士の演算

In [16]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2次元配列

c = np.array([[2, 0, 1],
              [5, 3, 4]])  # 2次元配列

print(b)
print()
print(c)
print()
print(b + c)
print()
print(b * c)

[[0 1 2]
 [3 4 5]]

[[2 0 1]
 [5 3 4]]

[[2 1 3]
 [8 7 9]]

[[ 0  0  2]
 [15 12 20]]


▲リスト2.41：インデックスを指定し、配列の要素にアクセスする

In [17]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a[3])  # インデックスを指定

4


▲リスト2.42：インデックスを指定して、配列の要素を入れ替える

In [18]:
a[2] = 9
print(a)

[1 2 9 4 5]


▲リスト2.43：2次元配列の要素にアクセスする

In [19]:
b = np.array([[0, 1, 2],
              [3, 4, 5]])

print(b[1, 2])  # b[1][2]と同じ

5


▲リスト2.44：2次元配列の要素を入れ替える

In [20]:
b[1, 2] = 9

print(b)

[[0 1 2]
 [3 4 9]]


▲リスト2.45：行や列にアクセスする

In [21]:
c = np.array([[0, 1, 2],
              [3, 4, 5]])

print(c[1, :])  # インデックスが1の行を取得

print()

c[:, 1] = np.array([6, 7])  # インデックスが1の列を入れ替え
print(c)

[3 4 5]

[[0 6 2]
 [3 7 5]]


▲リスト2.46：関数の引数、および返り値としての配列

In [22]:
import numpy as np

def my_func(x):
    y = x * 2 + 1
    return y

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2次元配列
b = my_func(a)  # 引数として配列を渡し、返り値として配列を受け取る

print(b)

[[ 1  3  5]
 [ 7  9 11]]


▲リスト2.47：NumPyが持つ様々な関数

In [23]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])  # 2次元配列

print("合計:", np.sum(a))
print("平均:", np.average(a))
print("最大値:", np.max(a))
print("最小値:", np.min(a))

合計: 15
平均: 2.5
最大値: 5
最小値: 0


#### □問題

　Jupyter NotebookのセルにNumPyの2次元配列を2つ記述して、お互いの和、差、積を求めてみましょう（ リスト2.48 ）。

#### □解答例

▲リスト2.48：解答例

In [24]:
import numpy as np

a = np.array([[0, 1, 2],
              [3, 4, 5]])
b = np.array([[5, 4, 3],
              [2, 1, 0]])

print(a + b)  # 和
print()
print(a - b)  # 差
print()
print(a * b)  # 積

[[5 5 5]
 [5 5 5]]

[[-5 -3 -1]
 [ 1  3  5]]

[[0 4 6]
 [6 4 0]]
